### ISSUE TITLE
考虑对矩形头像的支持

### ISSUE THREAD

**Issue by ttdevs** [Carbs0126/AvatarImageView#3]
可以考虑对矩形头像的支持，这个也是比较常用的，而且是在同一项目中。

**Comment by Carbs0126** [comment]
嗯，谢谢提醒，矩形的应用确实不少，比如github就是采用的矩形+圆角的方式，近期我会加上的，谢谢

**Comment by Carbs0126** [comment]
已经加上了，使用SquareAvatarImageView
