### ISSUE TITLE
关于rxjava

### ISSUE THREAD

**Issue by dicallc** [Carbs0126/AvatarImageView#5]
对于RXJAVA 和RXandroid 其实这两个库都是重量级别的库，为啥好用很多人不用就是因为方法数太庞大了， 建议还是去掉依赖吧，影响开发者选择你的库

**Comment by Carbs0126** [comment]
谢谢提醒，已经改了，去掉了rx库

**Comment by Carbs0126** [comment]
compile 'cn.carbs.android:AvatarImageView:1.0.4'
